name: IPTV Update

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  

    steps:
    
      - name: Script çalıştır
        run: python scraper.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto update M3U"
          git diff --cached --quiet || git push
