name: IPTV Update

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Chrome kur
        uses: browser-actions/setup-chrome@v1

      - name: ChromeDriver kur
        uses: nanasess/setup-chromedriver@v2

      - name: Kütüphaneler
        run: |
          pip install selenium

      - name: Script çalıştır
        run: python update.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto update M3U"
          git diff --cached --quiet || git push
